# Example config file

[[Areas]]
name = "Fencing"
admin = "400"
db = "idk"

[[Areas]]
name = "Visual Arts"
admin = "401"
db = "idk"

[[Areas]]
name = "Industrial Arts"
admin = "402"
db = "idk"

[[Areas]]
name = "Cross Country"
admin = "402"
db = "idk"
