version: "3"
services:
  api:
    build: .
    depends_on:
      - db
    restart: always
    networks:
      - network
    ports:
      - 8000:8000
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - network
    expose:
      - 5432
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: apheleia
    command: postgres -c listen_addresses="*"
networks:
  network:
volumes:
  db-data:
