[package]
name = "apheleia_proc"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "*"
syn = { version = "1", features = ["extra-traits", "full"] }
toml = "*"
serde = { version = "*", features = ["derive"] }
proc-macro2 = "*"
hashbrown = "*"
