[package]
name = "apheleia"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "*", features = ["full"] }
actix-web = "4.0.0-beta.14"
futures = "*"
thiserror = "*"
# serde_json = "*"
# serde = { version = "*", features = ["derive"] }
log = "*"
